about/urls.py
from django.urls import path

from about import views

app_name='about'
urlpatterns = [
    path('', views.index, name='Index'),
]

blog/urls.py
from django.urls import path

from blog import views

app_name='blog'
urlpatterns = [
   path('', views.allBlogs, name='Index'),
   path('my-blogs', views.myBlogs, name='MyBlogs'),
   path('create', views.createBlog, name='Create'),
   path('<int:blogId>', views.detailBlog, name='Detail'),
   path('edit/<int:blogId>', views.editBlog, name='Edit'),
   path('delete/<int:blogId>', views.deleteBlog, name="Delete"),
   # path('all', views.allBlogs, name='All'),
]

chat/urls.py
from django.urls import path

from chat import views

app_name='chat'

urlpatterns = [
    path('', views.index, name='Index'),
    path('<str:username>', views.chat, name='Room'),
]

desafio_python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

app_name='home'

urlpatterns = [
    path('', views.index, name='Index'),
]

user/urls.py
from django.urls import path

from user import views

app_name='user'
urlpatterns = [
   path('register', views.register, name='Register'),
   path('login', views.login_request, name='Login'),
   path('logout', views.logout_request, name='Logout'),
   path('profile', views.user_update, name='Profile'),
   path('profile/avatar', views.avatar_load, name='Avatar'),
]

home/views.py
from django.shortcuts import render

from blog.models import Blog

# Create your views here.
def index(request):
  featuredBlogs = Blog.objects.all()[1:4].values()
  return render(request, 'home/index.html',{"featuredBlogs": featuredBlogs} )

home/templates/home/index.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}
<header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">Bienvenidos al Blog de Coderhouse!!</h1>
                    <p class="lead fw-normal text-white-50 mb-4">Esta pagina es el desafío final del curso de Python en
                        CoderHouse donde tenemos que hacer una web estilo blog utilizando Django</p>

                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5"
                    src="https://res.cloudinary.com/matitoledo/image/upload/v1654897277/coder00_z8nj1i.webp"
                    alt="..." /></div>
        </div>
    </div>
</header>
<!-- Blog preview section-->
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder" style="margin-bottom: 30px">Algunos Blogs</h2>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            {% for blog in featuredBlogs %}
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="/media/{{blog.image}}" alt="..." />
                    <div class="card-body p-4">
                        <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:Detail' blog.id %}">
                            <div class="h5 card-title mb-3">{{blog.title}}</div>
                        </a>
                        <div style="text-overflow: ellipsis;
                        overflow: hidden;
                        white-space: wrap;
                        height: 100px;">
                            {{blog.body | safe}}
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" width="50" height="50" style="border-radius: 50%;"
                                    src="{{blog.user_avatar}}" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">{{blog.user_name}}</div>
                                    <div class="text-muted">{{blog.date}}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

home/templates/home/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Blogs CoderHouse</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
</head>

<body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="{% url 'home:Index' %}">Blog Coderhouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'home:Index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about:Index' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:Index' %}">Blogs</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog:MyBlogs' %}">Mis Blogs</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'chat:Index' %}">Chat</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user:Profile' %}">Mi perfil</a>
                        </li>
                        {% else %}
                        <li class="nav-item"><a class="btn btn-primary" href="{% url 'user:Login' %}">Sign In</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto">
                        <div class="small m-0 text-white">Copyright &copy; Your Website 2022</div>
                    </div>
                    <div class="col-auto">
                        <a class="link-light small" href="#!">Privacy</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Terms</a>
                        <span class="text-white mx-1">&middot;</span>
                        <a class="link-light small" href="#!">Contact</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
</body>

</html>