blog/urls.py
from django.urls import path

from blog import views

app_name='blog'
urlpatterns = [
   path('', views.allBlogs, name='Index'),
   path('my-blogs', views.myBlogs, name='MyBlogs'),
   path('create', views.createBlog, name='Create'),
   path('<int:blogId>', views.detailBlog, name='Detail'),
   path('edit/<int:blogId>', views.editBlog, name='Edit'),
   path('delete/<int:blogId>', views.deleteBlog, name="Delete"),
   # path('all', views.allBlogs, name='All'),
]

chat/urls.py
from django.urls import path

from chat import views

app_name='chat'

urlpatterns = [
    path('', views.index, name='Index'),
    path('<str:username>', views.chat, name='Room'),
]

desafio_python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Chat(models.Model):
  user_one = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='user_one')
  user_two = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name='user_two')
  
  def __str__(self):
        return f'{self.user_one} and {self.user_two} '

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.CharField(max_length=100)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    text = models.TextField(max_length=500) # what length you want

chat/forms.py
from django.forms import ModelForm
from chat.models import Message


class MessageForm(ModelForm):
  class Meta:
    model = Message
    fields = ['text' ]

chat/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth import get_user_model
from chat.forms import MessageForm
from chat.models import Chat, Message
from user.models import Avatar
# Create your views here.

def getuserlist(request):
  users = get_user_model().objects.all().values()
  user_list = []
  for user in users:
    if user["username"] != "admin" and user["username"] != request.user.username:
      user_list.append(user)

  for user in user_list:
    try:
      avatar = Avatar.objects.get(user_id=user['id']).image.url
    except Avatar.DoesNotExist:
      avatar = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E"
    user["avatar"] = avatar
  
  return user_list

def search(q, userlist):
  if q == "":
    result = userlist
  else:
    filtrada = []

    for user in userlist:
      if q in user["username"]:
        filtrada.append(user)
      
    result = filtrada
  
  return result

# ----------------------------------------------------------------------------------------------------

def index(request):
  users_list = getuserlist(request)
  
  if request.GET:
    q = request.GET['q']
    users_list = search(q, users_list)
      
    return render(request, 'chat/index.html', {"users": users_list} )

  return render(request, 'chat/index.html', {"users": users_list} )

# ----------------------------------------------------------------------------------------------------

def chat(request, username):
  users_list = getuserlist(request)

  user_to_chat = get_user_model().objects.get(username=username)
  try:
    avatar = Avatar.objects.get(user_id=user_to_chat.id).image.url
  except Avatar.DoesNotExist:
    avatar = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E"
  
  try:
    my_avatar = Avatar.objects.get(user=request.user).image.url
  except Avatar.DoesNotExist:
    my_avatar = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E"
  
  search_chat = Chat.objects.filter(user_one=request.user, user_two=user_to_chat) or Chat.objects.filter(user_two=request.user, user_one=user_to_chat)
  if not search_chat.exists():
    chat = Chat.objects.create(user_one=request.user, user_two=user_to_chat)
  else:
    chat = search_chat[0]

  messages = Message.objects.filter(chat=chat).values()
  form = MessageForm()

  if request.GET:
    q = request.GET['q']
    users_list = search(q, users_list)
      
    return render(request, 'chat/index.html', {"users": users_list, "user_to_chat": user_to_chat, "avatar":avatar, "messages": messages, "my_avatar": my_avatar} )
  
  if request.method == 'POST':
    form = MessageForm(request.POST)  
    if form.is_valid():
      info = form.cleaned_data
      time = datetime.datetime.now().strftime('%H:%M')
      message = Message(user=request.user, chat=chat, text=info['text'],time=time)
      message.save()
      return render(request, 'chat/index.html', {"users": users_list, "user_to_chat": user_to_chat, "avatar":avatar, "messages": messages, "my_avatar": my_avatar} )
  return render(request, 'chat/index.html', {"users": users_list, "user_to_chat": user_to_chat, "avatar":avatar, "messages": messages, "my_avatar": my_avatar} )

chat/templates/chat/index.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
	<!--  All snippets are MIT license http://bootdey.com/license -->
	<title>white chat - Bootdey.com</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
	<main class="content" style="margin: 20px;">
		<div class="container p-0">
			<div class="card">
				<!-- DIVIDE IZQUIERDA Y DERECHA -->
				<div class="row g-0">
					<!-- COLUMNA IZQUIERDA -->
					<div class="col-12 col-lg-5 col-xl-3 border-right">
						<!-- BUSCADOR -->
						<div class="px-4 d-none d-md-block">
							<div class="d-flex align-items-center">
								<div class="flex-grow-1">
									<form method="GET">
										<input type="text" id='q' name='q' class="form-control my-3" placeholder="Search...">
									</form>
								</div>
							</div>
						</div>
						<!-- LISTADO USUARIOS -->
						{% for user in users %}
						<a href="{% url 'chat:Room' user.username %}" class="list-group-item list-group-item-action border-0"
							style="border-bottom: 1px solid #dee2e6 !important;">
							<div class="d-flex align-items-start">
								<img src='{{user.avatar}}' class="rounded-circle mr-1" alt="Vanessa Tucker" width="40" height="40">
								<div class="flex-grow-1 ml-3" style="margin-top: 8px;">
									{{user.username}}
								</div>
							</div>
						</a>
						{% endfor %}
						<hr class="d-block d-lg-none mt-1 mb-0">
					</div>
					<!-- COLUMNA DERECHA -->
					{% if user_to_chat %}
					<div class="col-12 col-lg-7 col-xl-9" style="min-height: calc(100vh - 170px);">
						<!-- ENCABEZADO -->
						<div class="py-2 px-4 border-bottom d-none d-lg-block">
							<div class="d-flex align-items-center py-1">
								<div class="position-relative">
									<img src="{{avatar}}" class="rounded-circle mr-1" alt="Sharon Lessman" width="40" height="40">
								</div>
								<div class="flex-grow-1 pl-3">
									<strong>{{user_to_chat.first_name}} {{user_to_chat.last_name}}</strong>
								</div>
							</div>
						</div>
						<!-- COLUMNA MENSAJES -->
						<div class="position-relative">
							<!-- MENSAJES -->
							<div class="chat-messages p-4">
								{% for message in messages %}
								{% if request.user.id == message.user_id %}
								<div class="chat-message-right pb-4">
									<div>
										<img src="{{my_avatar}}" class="rounded-circle mr-1" width="40" height="40">
										<div class="text-muted small text-nowrap mt-2">{{message.time}}</div>
									</div>
									<div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
										<div class="font-weight-bold mb-1">Tú</div>
										{{message.text}}
									</div>
								</div>
								{% else %}
								<div class="chat-message-left pb-4">
									<div>
										<img src="{{avatar}}" class="rounded-circle mr-1" width="40" height="40">
										<div class="text-muted small text-nowrap mt-2">{{message.time}}</div>
									</div>
									<div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
										<div class="font-weight-bold mb-1">{{user_to_chat.first_name}} {{user_to_chat.last_name}}</div>
										{{message.text}}
									</div>
								</div>
								{% endif %}
								{% endfor %}
							</div>
						</div>
						<!-- INPUT MENSAJE -->
						<div class="flex-grow-0 py-3 px-4 border-top">
							<form method="POST" class="input-group"> {% csrf_token %}
								<tr>
									<td>
										<input name="text" class="form-control" maxlength="500" required id="id_text"
											placeholder="Escribe tu mensaje ...">
										</input>
										<button type="submit" class="btn btn-primary">Enviar</button>
									</td>
								</tr>
							</form>
						</div>
						<!-- FINAL -->
					</div>
					{%else%}
					<div class="col-12 col-lg-7 col-xl-9"
						style="min-height: calc(100vh - 170px); display: flex; justify-content: center; align-items: center;">
						<h1>Elegí con quien chatear</h1>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</main>

	<style type="text/css">
		.chat-online {
			color: #34ce57
		}

		.chat-offline {
			color: #e4606d
		}

		.chat-messages {
			display: flex;
			flex-direction: column;
			height: calc(100vh - 300px);
			overflow-y: scroll
		}

		.chat-message-left,
		.chat-message-right {
			display: flex;
			flex-shrink: 0
		}

		.chat-message-left {
			margin-right: auto
		}

		.chat-message-right {
			flex-direction: row-reverse;
			margin-left: auto
		}

		.py-3 {
			padding-top: 1rem !important;
			padding-bottom: 1rem !important;
		}

		.px-4 {
			padding-right: 1.5rem !important;
			padding-left: 1.5rem !important;
		}

		.flex-grow-0 {
			flex-grow: 0 !important;
		}

		.border-top {
			border-top: 1px solid #dee2e6 !important;
		}
	</style>

	<script type="text/javascript">

	</script>
</body>

</html>
{% endblock %}