blog/urls.py
from django.urls import path

from blog import views

app_name='blog'
urlpatterns = [
   path('', views.allBlogs, name='Index'),
   path('my-blogs', views.myBlogs, name='MyBlogs'),
   path('create', views.createBlog, name='Create'),
   path('<int:blogId>', views.detailBlog, name='Detail'),
   path('edit/<int:blogId>', views.editBlog, name='Edit'),
   path('delete/<int:blogId>', views.deleteBlog, name="Delete"),
   # path('all', views.allBlogs, name='All'),
]

desafio_python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
class Blog(models.Model):
  title = models.CharField(max_length=50)
  subtitle = models.CharField(max_length=100)
  body = RichTextUploadingField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='blogs', null=True, blank=True)
  date = models.CharField(max_length=100)
  user_name = models.CharField(max_length=100, default=None)
  user_avatar = models.TextField(default=None)

  def __str__(self):
    return f'Titulo: {self.title}'

blog/forms.py
from django.forms import ModelForm
from blog.models import Blog


class BlogForm(ModelForm):
  class Meta:
    model = Blog
    fields = ['title', 'subtitle', 'body', 'image', ]

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
import datetime
from blog.forms import BlogForm
from blog.models import Blog
from django.contrib.auth.models import User
from user.models import Avatar


# Create your views here.
def index(request):
  mainBlog = Blog.objects.filter(title='Como creamos esta página?').values()
  featuredBlogs = Blog.objects.all()[1:4].values()
  return render(request, 'blog/index.html', {"mainBlog": mainBlog[0], "featuredBlogs": featuredBlogs})

# ----------------------------------------------------------------------------------------------------

def myBlogs(request):
  myBlogs = Blog.objects.filter(user=request.user).values()
  return render(request, 'blog/my-blogs.html', {"myBlogs": myBlogs})

# ----------------------------------------------------------------------------------------------------

def createBlog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)  
        if form.is_valid() and len(request.FILES) != 0:
            info = form.cleaned_data
            date = datetime.date.today().strftime("%B %d, %Y")
            user = request.user
            image = request.FILES['image']
            user_name = User.objects.get(username=request.user).get_full_name()
            avatar = Avatar.objects.filter(user=request.user.id)
            if len(avatar) == 0:
              user_avatar = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E"
            else:
              user_avatar = avatar[0].image.url
            blog = Blog(title=info['title'],subtitle=info['subtitle'],body=info['body'],image=image,date=date,user=user,user_name=user_name,user_avatar=user_avatar)
            blog.save()
            return redirect("home:Index")
    form = BlogForm()
    return render(request, "blog/create.html", {"form": form})

# ----------------------------------------------------------------------------------------------------

def detailBlog(request, blogId = None):
  blog = Blog.objects.filter(id=blogId).values()
  return render(request, "blog/detail-blog.html",{"blog":blog[0]})

# ----------------------------------------------------------------------------------------------------

def editBlog(request, blogId = None):
  blog = Blog.objects.get(id=blogId)
  if request.user != blog.user:
    return render(request, "blog/no-access.html",)
  
  if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)  
        if form.is_valid():
          info = form.cleaned_data
          blog.title = info["title"]
          blog.subtitle = info["subtitle"]
          blog.body = info["body"]
          blog.image = info["image"]
          blog.save()
          return redirect("home:Index")
  else:
    form = BlogForm(initial={"title": blog.title, "subtitle": blog.subtitle, "body": blog.body,})
  return render(request, "blog/edit.html", {"form": form})

# ----------------------------------------------------------------------------------------------------

def allBlogs(request):
  blogs = Blog.objects.all()
  return render(request, "blog/all.html", {"blogs": blogs})

# ----------------------------------------------------------------------------------------------------

def deleteBlog(request, blogId = None):
  blog = Blog.objects.get(id=blogId)
  if request.method == 'POST':
    blog.delete()
    return redirect("home:Index")

  return render(request, "blog/delete-blog.html", {"blog": blog})

blog/templates/blog/all.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}


<section class="py-5" style="min-height: calc(100vh - 128px);display: flex; align-items: center;">
  <div class="container px-5">
    <div class="text-center">
      {% if blogs %}
      <h2 class="fw-bolder" style="margin-bottom: 30px">Todos nuestros blogs</h2>
      {% else %}
      <h2 class="fw-bolder" style="margin-bottom: 30px">Aún no hay blogs</h2>
      <a class="btn btn-primary" type="submit" href="{% url 'blog:Create' %}"
        style="width: 300px;margin-bottom: 30px;">Crear Blog</a>
      {% endif %}
    </div>
    <div class="row gx-5">
      {% for blog in blogs %}
      <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
          <img class="card-img-top" src="/media/{{blog.image}}" alt="..." />
          <div class="card-body p-4">
            <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:Detail' blog.id %}">
              <div class="h5 card-title mb-3">{{blog.title}}</div>
            </a>
            <div style="text-overflow: ellipsis;
                      overflow: hidden;
                      white-space: wrap;
                      height: 100px;">
              {{blog.body | safe}}
            </div>
          </div>
          <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
            <div class="d-flex align-items-end justify-content-between">
              <div class="d-flex align-items-center">
                <img class="rounded-circle me-3" width="50" height="50" style="border-radius: 50%;"
                  src="{{blog.user_avatar}}" alt="..." />
                <div class="small">
                  <div class="fw-bold">{{blog.user_name}}</div>
                  <div class="text-muted">{{blog.date}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</section>

{% endblock %}

blog/templates/blog/create.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <h1 class="fw-bolder">Crear Blog</h1>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-9">
          <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            {{form.media}}
            <tr class="form-floating mb-3">
              <th><label style="margin-top: 10px" for="id_title">Titulo:</label></th>
              <td>
                <input class="form-control" type="text" name="title" maxlength="50" required id="id_title">
              </td>
            </tr>
            <tr class="form-floating mb-3">
              <th><label style="margin-top: 10px" for="id_subtitle">Subtitulo:</label></th>
              <td>
                <input class="form-control" type="text" name="subtitle" maxlength="100" required id="id_subtitle">
              </td>
            </tr>
            <tr class="form-floating mb-3">
              <th><label style="margin-top: 10px" for="id_body">Cuerpo:</label></th>
              <td>
                <div class="django-ckeditor-widget" data-field-id="id_body" style="display: inline-block;">
                  <textarea name="body" cols="40" rows="10" required id="id_body" data-processed="0"
                    data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}"
                    data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype"></textarea>
                </div>
              </td>
            </tr>
            <tr class="form-floating mb-3">
              <th><label style="margin-top: 10px" for="id_image">Imagen:</label></th>
              <td>
                <input class="form-control" type="file" name="image" accept="image/*" id="id_image">
              </td>
            </tr>
            <div class="alert alert-warning" role="alert" style="text-align: center;margin-top: 15px;">Asegurese de
              completar todos los
              campos antes de enviar</div>
            <button class="btn btn-primary" style="width: 100%;" type="submit">Crear</button>
          </form>
        </div>
      </div>
    </div>
</section>


{% endblock %}

blog/templates/blog/delete-blog.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5" style="min-height: calc(100vh - 128px); display: flex; align-items: center;">
  <div class="container px-5 my-5">
    <div class="row gx-5 justify-content-center">
      <div class="col-lg-8 col-xl-6">
        <div class="text-center">
          <form method="POST">{% csrf_token %}
            <h2 class="fw-bolder" style="margin-bottom: 30px">¿Estas seguro que quieres eliminar el blog
              "{{blog.title}}"?</h2>
            <input class="btn btn-primary" style="width: 250px;" type="submit" value="Eliminar" />
          </form>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

blog/templates/blog/detail-blog.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}


<!-- Page content-->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{blog.title}}</h1>
                    <h2 class="fw-normal mb-1 text-muted">{{blog.subtitle}}</h2>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{blog.date}} by {{blog.user_name}}</div>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="/media/{{blog.image}}" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    {{blog.body | safe}}
                </section>
            </article>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/edit.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}


<section class="py-5">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <h1 class="fw-bolder">Editar Blog</h1>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-9">
          <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
            {{form.media}}
            <tr>
              <th><label style="margin-top: 10px" for="id_title">Title:</label></th>
              <td>
                <input class="form-control" type="text" name="title" value="{{form.initial.title}}" maxlength="50"
                  required id="id_title">
              </td>
            </tr>
            <tr>
              <th><label style="margin-top: 10px" for="id_subtitle">Subtitle:</label></th>
              <td>
                <input class="form-control" type="text" name="subtitle" value="{{form.initial.subtitle}}"
                  maxlength="100" required id="id_subtitle">
              </td>
            </tr>
            <tr>
              <th><label style="margin-top: 10px" for="id_body">Body:</label></th>
              <td>
                <div class="django-ckeditor-widget" data-field-id="id_body" style="display: block;">
                  <textarea name="body" cols="40" rows="10" required id="id_body" data-processed="0"
                    data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 400, &quot;width&quot;: &quot;auto&quot;, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;extraPlugins&quot;: &quot;codesnippet&quot;, &quot;filebrowserUploadUrl&quot;: &quot;/ckeditor/upload/&quot;, &quot;filebrowserBrowseUrl&quot;: &quot;/ckeditor/browse/&quot;, &quot;language&quot;: &quot;en-us&quot;}"
                    data-external-plugin-resources="[]" data-id="id_body"
                    data-type="ckeditortype">{{form.initial.body}}</textarea>
                </div>
              </td>
            </tr>
            <tr>
              <th><label style="margin-top: 10px" for="id_image">Image:</label></th>
              <td>
                <input class="form-control" type="file" name="image" accept="image/*" id="id_image">
              </td>
            </tr>
            <div class="alert alert-warning" role="alert" style="text-align: center;margin-top: 15px;">Asegurese de
              completar todos los
              campos antes de enviar</div>
            <button class="btn btn-primary" style="width: 100%;" type="submit">Crear</button>
          </form>
        </div>
      </div>
    </div>
</section>


{% endblock %}

blog/templates/blog/index.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5">
    <div class="container px-5">
        <h1 class="fw-bolder fs-5 mb-4">Nuestro blog</h1>
        <div class="card border-0 shadow rounded-3 overflow-hidden">
            <div class="card-body p-0">
                <div class="row gx-0">
                    <div class="col-lg-6 col-xl-5 py-lg-5">
                        <div class="p-4 p-md-5">
                            <div class="badge bg-primary bg-gradient rounded-pill mb-2">Main</div>
                            <div class="h2 fw-bolder">{{mainBlog.title}}</div>
                            <div style="text-overflow: ellipsis;
                            overflow: hidden;
                            white-space: wrap;
                            height: 100px;">
                                {{mainBlog.body | safe}}
                            </div>
                            <a class="stretched-link text-decoration-none" href="{% url 'blog:Detail' mainBlog.id %}">
                                Leer más
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-7">
                        <div class="bg-featured-blog" style="background-image: url(/media/{{mainBlog.image}})"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog preview section-->
<section class="py-5">
    <div class="container px-5">
        <h2 class="fw-bolder fs-5 mb-4">Blogs destacados</h2>
        <div class="row gx-5">
            {% for blog in featuredBlogs %}
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="/media/{{blog.image}}" />
                    <div class="card-body p-4">
                        <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:Detail' blog.id %}">
                            <div class="h5 card-title mb-3">{{blog.title}}</div>
                        </a>
                        <div style="text-overflow: ellipsis;
                        overflow: hidden;
                        white-space: wrap;
                        height: 100px;">
                            {{blog.body | safe}}
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" width="50" height="50" style="border-radius: 50%;"
                                    src="{{blog.user_avatar}}" alt="..." />
                                <div class="small">
                                    <div class="fw-bold">{{blog.user_name}}</div>
                                    <div class="text-muted">{{blog.date}}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="text-end mb-5 mb-xl-0">
            <a class="text-decoration-none" href="{% url 'blog:All' %}">
                Mas Blogs
                <i class="bi bi-arrow-right"></i>
            </a>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/blog/my-blogs.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5" style="min-height: calc(100vh - 128px); display: flex; align-items: center;">
  <div class="container px-5 my-5">
    <div class="row gx-5 justify-content-center">
      <div class="col-lg-8 col-xl-6">
        <div class="text-center">
          {% if not myBlogs %}
          <h2 class="fw-bolder" style="margin-bottom: 30px">No tienes blogs propios</h2>
          {% else %}
          <h2 class="fw-bolder" style="margin-bottom: 30px">Mis Blogs</h2>
          {% endif %}
          <a class="btn btn-primary" type="submit" href="{% url 'blog:Create' %}"
            style="width: 300px;margin-bottom: 30px;">Crear Blog</a>
        </div>
      </div>
    </div>
    <div class="row gx-5">
      {% for blog in myBlogs %}
      <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-0">
          <img class="card-img-top" src="/media/{{blog.image}}" alt="..." />
          <div class="card-body p-4">
            <a class="text-decoration-none link-dark stretched-link" href="{% url 'blog:Detail' blog.id %}">
              <div class=" h5 card-title mb-3">{{blog.title}}
              </div>
            </a>
            <div style="text-overflow: ellipsis;
                      overflow: hidden;
                      white-space: wrap;
                      height: 100px;">
              {{blog.body | safe}}
            </div>
          </div>
          <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
            <div class="small">
              <div class="text-muted">{{blog.date}}</div>
            </div>
          </div>
        </div>
        <div style="display: grid;width: auto;grid-template-columns: 1fr 1fr;">
          <a href="{% url 'blog:Edit' blog.id %}">
            <button type="button" class="btn btn-info" style="width: 100%;">Editar</button>
          </a>
          <a href="{% url 'blog:Delete' blog.id %}">
            <button type=" button" class="btn btn-danger" style="width: 100%;">Eliminar</button>
          </a>

        </div>
        <!-- <a href="{% url 'blog:Edit' blog.id %}">
          <button type="button" class="btn btn-secondary" style="width: 100%;">Editar</button>
        </a> -->
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

blog/templates/blog/no-access.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5"
  style="height: calc(100vh - 128px); min-height: cal(100vh - 128px); display: flex; align-items: center;">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <h1 class="fw-bolder">No puedes editar este Blog ya que no eres su creador</h1>
      </div>
    </div>
</section>


{% endblock %}