blog/urls.py
from django.urls import path

from blog import views

app_name='blog'
urlpatterns = [
   path('', views.allBlogs, name='Index'),
   path('my-blogs', views.myBlogs, name='MyBlogs'),
   path('create', views.createBlog, name='Create'),
   path('<int:blogId>', views.detailBlog, name='Detail'),
   path('edit/<int:blogId>', views.editBlog, name='Edit'),
   path('delete/<int:blogId>', views.deleteBlog, name="Delete"),
   # path('all', views.allBlogs, name='All'),
]

desafio_python/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user import views

app_name='user'
urlpatterns = [
   path('register', views.register, name='Register'),
   path('login', views.login_request, name='Login'),
   path('logout', views.logout_request, name='Logout'),
   path('profile', views.user_update, name='Profile'),
   path('profile/avatar', views.avatar_load, name='Avatar'),
]

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars', null=True, blank=True)

    def __str__(self):
        return f'url: {self.image.url}'

user/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from user.models import Avatar


class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label='Nombre de usuario', min_length=3)
    first_name = forms.CharField(label='Nombre', min_length=3)
    last_name = forms.CharField(label='Apellido', min_length=3)
    email = forms.EmailField(label='Correo electrónico')
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar la contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {k: "" for k in fields}

#----------------------------------------------------------------------------------------------------

class UserEditForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name' ]
        widgets = {
            'email': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

#----------------------------------------------------------------------------------------------------

class AvatarForm(ModelForm):
    class Meta:
        model = Avatar
        fields = ('image', )

user/views.py
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect
from user.forms import AvatarForm, UserEditForm, UserRegisterForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from user.models import Avatar
import os



# Create your views here.


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("user:Login")
        else:
            return render(request, "user/register.html", {"form": form, "errors": form.errors})
    form = UserRegisterForm()
    return render(request, "user/register.html", {"form": form})

# ----------------------------------------------------------------------------------------------------


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home:Index")

        return render(request, "user/login.html", {'form': form})

    form = AuthenticationForm()
    return render(request, "user/login.html", {'form': form})

# ----------------------------------------------------------------------------------------------------


def logout_request(request):
    logout(request)
    return redirect("user:Login")

# ----------------------------------------------------------------------------------------------------


@login_required
def user_update(request):
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home:Index')
    

    form = UserEditForm(model_to_dict(user))
    avatares = Avatar.objects.filter(user=user.id)
    if len(avatares) == 0:
      url = "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/271deea8-e28c-41a3-aaf5-2913f5f48be6/de7834s-6515bd40-8b2c-4dc6-a843-5ac1a95a8b55.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI3MWRlZWE4LWUyOGMtNDFhMy1hYWY1LTI5MTNmNWY0OGJlNlwvZGU3ODM0cy02NTE1YmQ0MC04YjJjLTRkYzYtYTg0My01YWMxYTk1YThiNTUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.BopkDn1ptIwbmcKHdAOlYHyAOOACXW0Zfgbs0-6BY-E"
    else:
      url = avatares[0].image.url
    return render(request, "user/profile.html", {'form': form, "url": url})

# ----------------------------------------------------------------------------------------------------

@login_required
def avatar_load(request):
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid  and len(request.FILES) != 0:
            image = request.FILES['image']
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            return redirect('home:Index')

    form= AvatarForm()
    return render(request, "user/avatar.html",{"form": form})

user/templates/user/avatar.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<section class="py-5"
  style="height: calc(100vh - 128px); min-height: cal(100vh - 128px); display: flex; justify-content: center; align-items: center;">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <h1 class="fw-bolder">Carga tu Avatar!</h1>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-6">
          <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <tr>
              <th><label for="id_image" style="margin-top: 10px">Imagen:</label></th>
              <td>
                <input class="form-control" type="file" name="image" accept="image/*" id="id_image">
              </td>
            </tr>
            {% if errors %}
            {% for error in errors.image %}
            <p style="color: red; margin: 2px;">{{error}}</p>
            {% endfor %}
            {% endif %}
            <button class="btn btn-primary" style="width: 540px; margin-top: 20px" type="submit">Cargar
              avatar</button>
          </form>
        </div>
      </div>
    </div>
</section>


{% endblock %}

user/templates/user/login.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}

<section class="py-5"
  style="height: calc(100vh - 128px); min-height: cal(100vh - 128px); display: flex; justify-content: center; align-items: center;">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <h1 class="fw-bolder">Iniciar sesion</h1>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-6">
          <form method="POST">{% csrf_token %}
            <tr class="form-floating mb-3">
              <th><label for="id_username" style="margin-top: 10px">Nombre de usuario:</label></th>
              <td>
                <input class="form-control" type="text" name="username" autofocus autocapitalize="none"
                  autocomplete="username" maxlength="150" required id="id_username">
              </td>
              {% if errors %}
              {% for error in errors.username %}
              <p style="color: red; margin: 2px;">{{error}}</p>
              {% endfor %}
              {% endif %}
            </tr>
            <tr class="form-floating mb-3">
              <th><label for="id_password" style="margin-top: 10px">Contraseña:</label></th>
              <td>
                <input class="form-control" type="password" name="password" autocomplete="current-password" required
                  id="id_password">
              </td>
              {% if errors %}
              {% for error in errors.password %}
              <p style="color: red; margin: 2px;">{{error}}</p>
              {% endfor %}
              {% endif %}
            </tr>

            <button class="btn btn-primary" style="width: 540px; margin-top: 10px" type="submit">Iniciar
              sesion</button>
          </form>
          <a href="{% url 'user:Register' %}" style="display: flex; justify-content: center; margin-top: 20px;">
            <button type="button" class="btn btn-link">Registrarse</button>
          </a>
        </div>
      </div>
    </div>
</section>

{% endblock %}

user/templates/user/profile.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<section class="py-5">
  <div class="container px-5">
    <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
      <div class="text-center mb-5">
        <img src="{{url}}" width="100" height="100" style="border-radius: 50%; margin-bottom: 15px;">
        <h1 class="fw-bolder">Perfil de {{user.username}}</h1>
      </div>
      <div class="row gx-5 justify-content-center">
        <div class="col-lg-8 col-xl-6">
          <form action="" method="POST">{% csrf_token %}
            <form method="POST">{% csrf_token %}
              <tr>
                <th><label for="id_email" style="margin-top: 10px">Email address:</label></th>
                <td>
                  <input type="text" class="form-control" name="email" value="{{form.email.value}}" readonly="readonly"
                    maxlength="254" id="id_email">
                </td>
                {% if errors %}
                {% for error in errors.username %}
                <p style="color: red; margin: 2px;">{{error}}</p>
                {% endfor %}
                {% endif %}
              </tr>
              <tr>
                <th><label for="id_first_name" style="margin-top: 10px">Nombre:</label></th>
                <td>
                  <input class="form-control" type="text" value="{{form.first_name.value}}" name="first_name"
                    maxlength="150" id="id_first_name">
                </td>
              </tr>
              <tr>
                <th><label for="id_last_name" style="margin-top: 10px">Apellido:</label></th>
                <td>
                  <input class="form-control" type="text" value="{{form.last_name.value}}" name="last_name"
                    maxlength="150" id="id_last_name">
                </td>
              </tr>
              <a href="{% url 'user:Avatar' %}">
                <button type="button" style="width: 540px; margin-top: 10px" class="btn btn-secondary">Agregar/modificar
                  foto</button>
              </a>
              <button class="btn btn-primary" style="width: 540px; margin-top: 20px" type="submit">Editar
                perfil</button>
            </form>
          </form>
          <a href="{% url 'user:Logout' %}">
            <button type="button" style="width: 540px; margin-top: 60px" class="btn btn-warning">Cerrar sesión</button>
          </a>
        </div>
      </div>
    </div>
</section>


{% endblock %}

user/templates/user/register.html
{% extends "home/layout.html" %}
{% load static %}
{% block content %}



<section class="py-5">
    <div class="container px-5">
        <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
            <div class="text-center mb-5">
                <h1 class="fw-bolder">Registrarse</h1>
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <form action="" method="POST">{% csrf_token %}
                        <form method="POST">{% csrf_token %}
                            <tr class="form-floating mb-3">
                                <th><label for="id_username" style="margin-top: 10px">Nombre de usuario:</label></th>
                                <td>
                                    <input class="form-control" type="text" name="username" minlength="3" autofocus
                                        required id="id_username">
                                </td>
                                {% if errors %}
                                {% for error in errors.username %}
                                <p style="color: red; margin: 2px;">{{error}}</p>
                                {% endfor %}
                                {% endif %}
                            </tr>
                            <tr class="form-floating mb-3">
                                <th><label style="margin-top: 10px" for="id_first_name">Nombre:</label></th>
                                <td>
                                    <input class="form-control" type="text" name="first_name" minlength="3" required
                                        id="id_first_name">
                                </td>
                            </tr>
                            <tr class="form-floating mb-3">
                                <th><label style="margin-top: 10px" for="id_last_name">Apellido:</label></th>
                                <td>
                                    <input class="form-control" type="text" name="last_name" minlength="3" required
                                        id="id_last_name">
                                </td>
                            </tr>
                            <tr class="form-floating mb-3">
                                <th><label for="id_email" style="margin-top: 10px">Correo electrónico:</label></th>
                                <td>
                                    <input class="form-control" type="email" name="email" required id="id_email">
                                </td>
                                {% if errors %}
                                {% for error in errors.email %}
                                <p style="color: red; margin: 2px;">{{error}}</p>
                                {% endfor %}
                                {% endif %}
                            </tr>
                            <tr class="form-floating mb-3">
                                <th><label for="id_password1" style="margin-top: 10px">Contraseña:</label></th>
                                <td>
                                    <input class="form-control" type="password" name="password1" required
                                        id="id_password1">
                                </td>
                            </tr>
                            <tr class="form-floating mb-3">
                                <th><label for="id_password2" style="margin-top: 10px">Confirmar la contraseña:</label>
                                </th>
                                <td>
                                    <input class="form-control" type="password" name="password2" required
                                        id="id_password2">
                                </td>
                            </tr>
                            {% if errors %}
                            {% for error in errors.password2 %}
                            <p style="color: red; margin: 2px;">{{error}}</p>
                            {% endfor %}
                            {% endif %}
                            <button class="btn btn-primary" style="width: 540px; margin-top: 10px"
                                type="submit">Registrate</button>
                        </form>
                    </form>
                </div>
            </div>
        </div>
</section>
{% endblock %}